package org.btc.resource;

import io.smallrye.common.constraint.NotNull;
import jakarta.inject.Inject;
import jakarta.validation.Valid;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.btc.model.Account;
import org.btc.service.AccountService;
import org.eclipse.microprofile.openapi.annotations.Operation;

import java.util.List;

@Path("/account")
public class AccountResource {

    @Inject
    AccountService accountService;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Get all accounts in database, exposed for test purposes")
    public List<Account> getAllAccounts() {
        return accountService.getAllAccounts();
    }

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(summary = "Create new account")
    public Account createAccount(@Valid Account account) {
        //return the newly created account, uid and accountNumber should probably be generated by the backend and not be visible as a return value
        return accountService.createAccount(account);
    }

    @PATCH
    @Path("{accountNumber}/deposit/{funds}")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Deposit funds into an existing account by account number")
    public void depositFunds(@PathParam("accountNumber") Long accountNumber, @PathParam("funds") double funds) {
        //return new balance or simply no reponse with 200 OK
        accountService.depositIntoAccount(accountNumber, funds);
    }

    //probably better to encapsulate in an object to avoid the long path
    @PATCH
    @Path("{senderAccountNumber}/receiver/{receiverAccountNumber}/funds/{funds}")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Transfer funds between two accounts")
    public void transferFunds(@PathParam("senderAccountNumber") @NotNull Long senderAccountNumber, @PathParam("receiverAccountNumber") @NotNull Long receiverAccountNumber, @PathParam("funds") @NotNull double funds) {
        //there are more precise terms to describe sender and receiver of funds.
        accountService.transferFunds(senderAccountNumber, receiverAccountNumber, funds);
    }

    @GET
    @Path("/{accountNumber}/balance")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Get the balance for an existing account")
    public double getBalance(@PathParam("accountNumber") Long accountNumber) {
        return accountService.getAccountBalance(accountNumber);
    }

}
