package org.btc.resource;

import io.smallrye.common.constraint.NotNull;
import jakarta.inject.Inject;
import jakarta.validation.Valid;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.Response;
import org.btc.model.Account;
import org.btc.service.AccountService;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;

import java.util.List;

import static jakarta.ws.rs.core.MediaType.APPLICATION_JSON;

@Path("/account")
public class AccountResource {

    @Inject
    AccountService accountService;

    @GET
    @Produces(APPLICATION_JSON)
    @Operation(summary = "Get all accounts in database, exposed for test purposes")
    public List<Account> getAllAccounts() {
        return accountService.getAllAccounts();
    }

    @POST
    @Produces(APPLICATION_JSON)
    @Consumes(APPLICATION_JSON)
    @Operation(summary = "Create new account")
    @APIResponses({
            @APIResponse(responseCode = "201", description = "Ok", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Account.class))),
            @APIResponse(responseCode = "500", description = "Error", content = @Content(mediaType = "application/json"))
    })
    public Response createAccount(@Valid Account account) {
        //return the newly created account, uid and accountNumber should probably be generated by the backend and not be visible as a return value
        accountService.createAccount(account);
        return Response.status(201).entity(account).build();
    }

    @PATCH
    @Path("{accountNumber}/deposit/{funds}")
    @Produces(APPLICATION_JSON)
    @Operation(summary = "Deposit funds into an existing account by account number")
    public void depositFunds(
            @Parameter(description = "The account number to deposit funds into", required = true, schema = @Schema(example = "123345678"))
            @PathParam("accountNumber") Long accountNumber,
            @Parameter(description = "The amount to deposit", required = true, schema = @Schema(example = "1000000.0"))
            @PathParam("funds") double funds) {
        //return new balance or simply no reponse with 200 OK
        accountService.depositIntoAccount(accountNumber, funds);
    }

    //probably better to encapsulate in an object to avoid the long path
    @PATCH
    @Path("{senderAccountNumber}/receiver/{receiverAccountNumber}/funds/{funds}")
    @Produces(APPLICATION_JSON)
    @Operation(summary = "Transfer funds between two accounts")
    public void transferFunds(
            @Parameter(description = "The account number for the sender account", required = true, schema = @Schema(example = "112345678"))
            @PathParam("senderAccountNumber") @NotNull Long senderAccountNumber,
            @Parameter(description = "The account number for the receiver account", required = true, schema = @Schema(example = "193345678"))
            @PathParam("receiverAccountNumber") @NotNull Long receiverAccountNumber,
            @Parameter(description = "The amount funds to be sent", required = true, schema = @Schema(example = "450000"))
            @PathParam("funds") @NotNull double funds) {
        //there are more precise terms to describe sender and receiver of funds.
        accountService.transferFunds(senderAccountNumber, receiverAccountNumber, funds);
    }

    @GET
    @Path("/{accountNumber}/balance")
    @Produces(APPLICATION_JSON)
    @Operation(summary = "Get the balance for an existing account")
    @APIResponses({
            @APIResponse(responseCode = "200", content = @Content(mediaType = APPLICATION_JSON, schema = @Schema(example = "3500000"))),
            @APIResponse(responseCode = "500", description = "Internal error")
    })
    public double getBalance(
            @Parameter(description = "Account number to get balance for", required = true, schema = @Schema(example = "123345678"))
            @PathParam("accountNumber") Long accountNumber) {
        return accountService.getAccountBalance(accountNumber);
    }

}
